version: "3"

services:
  cli:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /src

volumes:
  bin:
  out: