on:
  push:
    branches:
      - main
      - develop

name: test sample app
jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm start
      